---

version: "3"

services:
  api:
    image: tapis/site-router-api
    ports:
      - 8000:8000
    volumes:
      - ./config-local.json:/home/tapis/config.json

  redis:
    image: redis
    ports:
      - 6379:6379
  
  tests:
    image: tapis/site-router-api
    environment:
      - TOKENS_API_TOKEN=<TODO_add_this>
    command: ["/home/tapis/test_run_entry.sh"]
