# Image: tapis/site-router-api

# For more information, please refer to https://aka.ms/vscode-docker-python
# FROM python:3.8-slim-buster
FROM python:3.8

EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

# add vim for debugging
RUN apt-get update && apt-get install -y vim

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 4872 --disabled-password --gecos "" tapis
USER tapis

WORKDIR /home/tapis
COPY configschema.json /home/tapis/configschema.json
COPY config-local.json /home/tapis/config.json
COPY service /home/tapis/service
COPY entry.sh /home/tapis/entry.sh
COPY test_run_entry.sh /home/tapis/test_run_entry.sh
USER root
RUN chmod +x /home/tapis/entry.sh
RUN chmod +x /home/tapis/test_run_entry.sh
RUN chown -R tapis:tapis /home/tapis

USER tapis
CMD ["/home/tapis/entry.sh"]